In [17]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset,DataLoader
import torch.optim as optim
import torch.nn as nn
import matplotlib.pyplot as plt

In [18]:
import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

Using Colab cache for faster access to the 'creditcardfraud' dataset.

In [19]:
df = pd.read_csv(path + '/creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [20]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [21]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [27]:
# normalize the amount
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train["Amount"] = scaler.fit_transform(X_train[["Amount"]])
X_test["Amount"] = scaler.fit_transform(X_test[["Amount"]])

In [29]:
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [28]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
2557,2105.0,-2.289565,-0.480260,0.818685,-1.706423,0.822102,-1.660326,0.944047,-0.541765,1.323156,...,-0.831985,-0.210837,0.914737,0.867888,0.422969,0.310584,-0.781488,0.392241,-0.147757,0.000039
247823,153702.0,-0.313717,-4.064342,-3.398445,0.704011,0.101662,1.529848,1.551670,-0.036774,0.015829,...,2.142593,0.853186,-0.091941,-0.936215,-0.833081,-0.498728,0.651183,-0.290331,0.110360,0.046486
152342,97283.0,-1.809763,-0.567439,2.265186,-0.960318,-1.212537,1.516493,-1.417176,0.903421,1.961027,...,-0.554004,-0.509915,-0.424978,-0.268621,0.010121,0.466862,0.835540,-0.062385,0.088079,0.002919
103385,68628.0,1.192319,0.178575,0.141491,0.459628,-0.049959,-0.112122,-0.163883,0.155740,-0.067566,...,-0.149985,-0.240464,-0.739862,0.116799,-0.373837,0.125470,0.130126,-0.016956,0.011937,0.000077
8771,11951.0,-0.963451,0.700311,1.097333,-1.547626,0.669966,0.513533,0.333683,0.270900,1.381880,...,0.122458,-0.279519,-0.470181,-0.124037,-1.388839,-0.237453,0.785347,0.349708,0.216207,0.001452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,75618.0,1.173488,0.100792,0.490512,0.461596,-0.296377,-0.213165,-0.165254,0.119221,-0.114199,...,-0.157534,-0.186027,-0.574283,0.161405,-0.006140,0.091444,0.109235,-0.020922,0.003967,0.000077
259178,159000.0,-0.775981,0.144023,-1.142399,-1.241113,1.940358,3.912076,-0.466107,1.360620,0.400697,...,-0.295730,0.037078,-0.019575,0.241830,0.682820,-1.635109,-0.770941,0.066006,0.137056,0.003473
131932,79795.0,-0.146609,0.992946,1.524591,0.485774,0.349308,-0.815198,1.076640,-0.395316,-0.491303,...,0.007155,0.052649,0.354089,-0.291198,0.402849,0.237383,-0.398467,-0.121139,-0.196195,0.000153
146867,87931.0,-2.948638,2.354849,-2.521201,-3.798905,1.866302,2.727695,-0.471769,2.217537,0.580199,...,0.417396,-0.332759,-1.047514,0.143326,0.678869,0.319710,0.426309,0.496912,0.335822,0.000039
121958,76381.0,1.233174,-0.784851,0.386784,-0.698559,-1.034018,-0.637028,-0.502369,-0.188057,-0.749637,...,0.337732,0.027634,-0.234522,-0.059544,-0.109073,0.290326,-0.393074,0.001217,0.038588,0.004398

In [32]:
# dataset class
class custom(Dataset):
  def __init__(self,features,labels):
    self.features = torch.tensor(features.values,dtype=torch.float32)
    self.labels = torch.tensor(labels.values,dtype=torch.long)

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index],self.labels[index]

In [33]:
train_dataset = custom(X_train,y_train)

In [34]:
test_dataset = custom(X_test,y_test)

In [36]:
# model architecture
class MyNN(nn.Module):

  def __init__(self,input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_rate):

    super().__init__()

    layers = []

    for i in range(num_hidden_layers):

      layers.append(nn.Linear(input_dim,neurons_per_layer))
      layers.append(nn.BatchNorm1d(neurons_per_layer))
      layers.append(nn.ReLU())
      layers.append(nn.Dropout(dropout_rate))
      input_dim = neurons_per_layer

    layers.append(nn.Linear(neurons_per_layer,output_dim))

    self.model = nn.Sequential(*layers)

  def forward(self,x):
    return self.model(x)

In [42]:
def objective(trial):
  # Define device at the start of the objective function
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")



  train_loader = DataLoader(train_dataset,batch_size=batch_size,shuffle=True)
  test_loader = DataLoader(test_dataset,batch_size=batch_size,shuffle=False)

  input_dim = X_train.shape[1] # Corrected input_dim based on data
  output_dim = len(y.unique()) # Corrected output_dim based on data

  model = MyNN(input_dim,output_dim,num_hidden_layers,nueron_per_layer,dropout_rate)
  model.to(device)

  #param init


  #optimizer
  criterion = nn.CrossEntropyLoss()

  if optimizer_name=='Adam':
    optimizer = optim.Adam(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
  elif optimizer_name=='SGD':
    optimizer = optim.SGD(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
  else:
    optimizer = optim.RMSprop(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
  #train loop
  for epoch in range(epochs):
    total_epoch_loss = 0
    for batch_features,batch_labels in train_loader:

      #step 3 gpu
      batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)

      #forawrd
      outputs = model(batch_features)
      # claculate
      loss = criterion(outputs,batch_labels)

      #back pass
      optimizer.zero_grad()#clear the gradient
      loss.backward()
      #update
      optimizer.step()

      total_epoch_loss += loss.item()

    avg_total = total_epoch_loss/len(train_loader)

    # model eval
    model.eval()
    # `import torch` is already present at the top of the notebook, removing redundant import.

    total = 0
    correct = 0
    accuracy_list=[]
    with torch.no_grad():
      for batch_features,batch_labels in test_loader:

        # move the data to gpu
        batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
        y_pred = model(batch_features)
        # Get the predicted class by finding the index with the maximum score
        predicted_classes = y_pred.argmax(dim=1)

        # Compare predicted classes with actual labels
        batch_accuracy = (predicted_classes == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

    overall_accuracy = sum(accuracy_list)/len(accuracy_list)

    return overall_accuracy

In [39]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.11.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.4 MB/s eta 0:00:00
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 23.7 MB/s eta 0:00:00
Downloading colorlog-6.11.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.18.5 colorlog-6.11.0 optuna-4.9.0

In [40]:
import optuna

study = optuna.create_study(direction='maximize')

[I 2026-07-20 15:09:28,628] A new study created in memory with name: no-name-8927b1d3-cbdf-4003-b8b4-d0d7f118025e

In [ ]:
study.optimize(objective,n_trials=50)

[I 2026-07-20 15:10:50,007] Trial 1 finished with value: 0.9984085377270174 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 64, 'epoch': 10, 'learning_rate': 0.027683013382919407, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'SGD', 'weight_decay': 2.628578520276898e-05}. Best is trial 1 with value: 0.9984085377270174.
[I 2026-07-20 15:10:58,036] Trial 2 finished with value: 0.9983987831426951 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 72, 'epoch': 20, 'learning_rate': 0.11510771125659648, 'dropout_rate': 0.1, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 0.00019476621513918007}. Best is trial 1 with value: 0.9984085377270174.
[I 2026-07-20 15:11:22,641] Trial 3 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 64, 'epoch': 30, 'learning_rate': 0.05192563090405576, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.0004290779652032592}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:11:28,394] Trial 4 finished with value: 0.9983987831426951 and parameters: {'num_hidden_layer': 2, 'nueron_per_layer': 80, 'epoch': 50, 'learning_rate': 0.12300741695557704, 'dropout_rate': 0.30000000000000004, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 0.00030635269690438866}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:11:40,113] Trial 5 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 24, 'epoch': 40, 'learning_rate': 0.07881712340250582, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 2.6501136889840225e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:11:58,424] Trial 6 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 120, 'epoch': 50, 'learning_rate': 0.0007830973476237394, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 6.190867550397093e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:12:46,066] Trial 7 finished with value: 0.9984085377270174 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 104, 'epoch': 10, 'learning_rate': 5.3203812908594434e-05, 'dropout_rate': 0.4, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 1.5313518402632034e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:12:52,683] Trial 8 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 1, 'nueron_per_layer': 120, 'epoch': 30, 'learning_rate': 7.204751333640246e-05, 'dropout_rate': 0.1, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 6.23326451822778e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:13:25,825] Trial 9 finished with value: 0.9984085377270174 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 32, 'epoch': 50, 'learning_rate': 0.0016756010902996535, 'dropout_rate': 0.2, 'batch_size': 16, 'optimizer': 'Adam', 'weight_decay': 9.2800498559332e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:13:34,471] Trial 10 finished with value: 0.9983987831426951 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 16, 'epoch': 40, 'learning_rate': 0.000641177800661946, 'dropout_rate': 0.30000000000000004, 'batch_size': 128, 'optimizer': 'Adam', 'weight_decay': 5.714476141633227e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:13:48,146] Trial 11 finished with value: 0.9984088356420816 and parameters: {'num_hidden_layer': 1, 'nueron_per_layer': 48, 'epoch': 30, 'learning_rate': 0.6597323186767047, 'dropout_rate': 0.5, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.0007717927336758449}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:13:57,038] Trial 12 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 8, 'epoch': 30, 'learning_rate': 0.010744511225748765, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.0009642462659812484}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:14:15,894] Trial 13 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 40, 'epoch': 40, 'learning_rate': 0.6678264724823301, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 1.2011014358762552e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:14:52,223] Trial 14 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 96, 'epoch': 40, 'learning_rate': 0.011265583650433814, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.00035656800710439995}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:15:10,699] Trial 15 finished with value: 0.9984088356420816 and parameters: {'num_hidden_layer': 2, 'nueron_per_layer': 56, 'epoch': 20, 'learning_rate': 0.07261389092436184, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.00013566109901004788}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:15:23,084] Trial 16 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 24, 'epoch': 40, 'learning_rate': 0.005512434352227016, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'Adam', 'weight_decay': 2.3530003986376086e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:15:44,366] Trial 17 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 2, 'nueron_per_layer': 88, 'epoch': 20, 'learning_rate': 0.2648507515237595, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.0005849984942262603}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:15:57,655] Trial 18 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 40, 'epoch': 30, 'learning_rate': 0.0359235843478095, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 3.2389914224486226e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:16:17,592] Trial 19 finished with value: 0.9984088356420816 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 8, 'epoch': 40, 'learning_rate': 0.0023925230524271973, 'dropout_rate': 0.30000000000000004, 'batch_size': 32, 'optimizer': 'Adam', 'weight_decay': 0.0003701549276147596}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:16:26,464] Trial 20 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 56, 'epoch': 30, 'learning_rate': 1.093594818309416e-05, 'dropout_rate': 0.2, 'batch_size': 64, 'optimizer': 'SGD', 'weight_decay': 0.0001841648244668721}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:16:36,773] Trial 21 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 2, 'nueron_per_layer': 24, 'epoch': 20, 'learning_rate': 0.21877548945033165, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 3.907395895530066e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:16:54,640] Trial 22 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 112, 'epoch': 50, 'learning_rate': 0.0006525096718855461, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 1.8398453493024283e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:17:14,785] Trial 23 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 128, 'epoch': 50, 'learning_rate': 0.00016787642669035546, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 4.96886545815302e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:17:46,631] Trial 24 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 72, 'epoch': 50, 'learning_rate': 0.029196082923820147, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 9.117916544362068e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:18:19,686] Trial 25 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 96, 'epoch': 40, 'learning_rate': 0.006947313668932682, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 8.546765230796041e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:18:33,440] Trial 26 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 80, 'epoch': 40, 'learning_rate': 0.0003279121233815473, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 1.0886339405642031e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:19:45,480] Trial 27 finished with value: 0.9984085377270174 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 128, 'epoch': 50, 'learning_rate': 0.002047763639997667, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 3.873987685144281e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:20:26,859] Trial 28 finished with value: 0.9984088356420816 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 112, 'epoch': 30, 'learning_rate': 0.04426960120153262, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.00013503045434284458}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:20:33,577] Trial 29 finished with value: 0.9983987831426951 and parameters: {'num_hidden_layer': 4, 'nueron_per_layer': 48, 'epoch': 40, 'learning_rate': 2.1069272887610266e-05, 'dropout_rate': 0.5, 'batch_size': 128, 'optimizer': 'SGD', 'weight_decay': 0.0005209229033753996}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:21:35,343] Trial 30 finished with value: 0.9984085377270174 and parameters: {'num_hidden_layer': 5, 'nueron_per_layer': 64, 'epoch': 10, 'learning_rate': 0.019873131591664674, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'Adam', 'weight_decay': 1.9519971372765787e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:21:43,265] Trial 31 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 3, 'nueron_per_layer': 24, 'epoch': 50, 'learning_rate': 0.3243772071128622, 'dropout_rate': 0.2, 'batch_size': 64, 'optimizer': 'SGD', 'weight_decay': 3.172725639373811e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:21:50,353] Trial 32 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 1, 'nueron_per_layer': 120, 'epoch': 30, 'learning_rate': 9.016134315529928e-05, 'dropout_rate': 0.1, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 6.370300640486958e-05}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:21:57,322] Trial 33 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 1, 'nueron_per_layer': 112, 'epoch': 30, 'learning_rate': 4.729283714251489e-05, 'dropout_rate': 0.1, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.00024050798269083777}. Best is trial 3 with value: 0.9984094311377245.
[I 2026-07-20 15:22:04,857] Trial 34 finished with value: 0.9984094311377245 and parameters: {'num_hidden_layer': 1, 'nueron_per_layer': 120, 'epoch': 20, 'learning_rate': 0.0002078356865921252, 'dropout_rate': 0.2, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.0001301304272738956}. Best is trial 3 with value: 0.9984094311377245.